### ISSUE TITLE
[Meta] Core Library Implementation

### ISSUE THREAD

**Issue by asadali214** [apimatic/core-lib-csharp#1]
Following tasks are required for the core library's completion:
- [x] Create a basic structure for C# project
- [x] Add CI/CD (through commit: https://github.com/apimatic/core-lib-csharp/commit/475490ccce921fe21d5544f53d62e144718cc40b)
- [x] Addition of Authentication core structure w/ unit tests
- [x] #2
- [x] #4
- [x] Creation of ApiCall
- [x] #7
- [x] Creation of Request and RequestBuilder
- [x] Creation of ResponseHandler
- [x] Creation of ResponseError
- [x] Creation of Context
- [x] #3
- [x] #10
- [x] #13
- [x] #12
- [x] #14
- [x] #11

**Comment by asadali214** [comment]
Released Core Library: https://www.nuget.org/packages/APIMatic.Core/0.1.0
ReleaseNotes: https://github.com/apimatic/core-lib-csharp/releases/tag/0.1.0

cc: @usamabintariq
